nifty_bank<-ts(niftybankaggr$Close,star=c(2000,1),freq=12)
gpr_ind<-ts(gpr_index_red1$GPRH,start = c(2000,1),freq=12)
com_ts<-cbind(nifty_bank,gpr_ind)
autoplot(com_ts)
nifty_bank %>% decompose()%>%autoplot()
gpr_ind %>% decompose()%>%autoplot()
mod<-tslm(nifty_bank ~ gpr_ind, data=com_ts)
summary(mod)
checkresiduals(mod)
