nifty_og<-ts(niftyogaggr$Close,star=c(2005,1),freq=12)
gpr_ind<-ts(gpr_index_red1$GPRH,start = c(2005,1),freq=12)
com_ts<-cbind(nifty_og,gpr_ind)
autoplot(com_ts)
nifty_og %>% decompose()%>%autoplot()
gpr_ind %>% decompose()%>%autoplot()
mod<-tslm(nifty_og ~ gpr_ind, data=com_ts)
summary(mod)
checkresiduals(mod)
